\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={speed-dating},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{speed-dating}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{}
    \preauthor{}\postauthor{}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{12 de novembro de 2019}


\begin{document}
\maketitle

\hypertarget{universidade-federal-de-campina-grande-ufcg}{%
\subsubsection{\texorpdfstring{\textbf{Universidade Federal de Campina
Grande \textbar{}
UFCG}}{Universidade Federal de Campina Grande \textbar{} UFCG}}\label{universidade-federal-de-campina-grande-ufcg}}

\hypertarget{ciuxeancia-da-computauxe7uxe3o}{%
\subsubsection{\texorpdfstring{\textbf{Ciência da Computação
}}{Ciência da Computação }}\label{ciuxeancia-da-computauxe7uxe3o}}

\hypertarget{ciuxeancia-de-dados-descritiva}{%
\subsubsection{\texorpdfstring{\textbf{Ciência de Dados
Descritiva}}{Ciência de Dados Descritiva}}\label{ciuxeancia-de-dados-descritiva}}

\hypertarget{professor-nazareno-andrade}{%
\subsubsection{\texorpdfstring{\textbf{Professor}: Nazareno
Andrade}{Professor: Nazareno Andrade}}\label{professor-nazareno-andrade}}

\hypertarget{alunoa-fabiana-alves-gomes}{%
\subsubsection{\texorpdfstring{\textbf{Aluno(a)}: Fabiana Alves
Gomes}{Aluno(a): Fabiana Alves Gomes}}\label{alunoa-fabiana-alves-gomes}}

\includegraphics{../dados/logo.png}

\newpage

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{introduuxe7uxe3o}{%
\subsection{Introdução}\label{introduuxe7uxe3o}}

Este relatório tem como objetivo elucidar uma pergunta utilizando os
dados de encontros relâmpagos, também conhecido como speed dating, tais
encontros tem uma duração de em média 4 minutos. O quanto a sinceridade
e o interesse em comum influenciam o like?

Após os breves encontros os participantes respondiam a um questionário
dizendo o que acharam sobre a pessoa com quem tiveram o encontro, no
total foram responsidos por volta de 5 mil questionários sobre os
encontros. Após o tratamento dos dados restaram um total de
\textbf{4024} respostas do questionário referente aos encontros que
podemos analisar.

Os dados¹ foram coletados em um experimento² pelos professores da
\textbf{\emph{Columbia Business School}}, que disponibilizaram os dados
para a comunidade.

\begin{itemize}
\tightlist
\item
  ¹ Dados -
  \url{https://github.com/nazareno/ciencia-de-dados-1/tree/master/5-regressao/speed-dating}
\item
  ² Experimento -
  \url{https://faculty.chicagobooth.edu/emir.kamenica/documents/genderDifferences.pdf}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{desenvolvimento}{%
\subsection{Desenvolvimento}\label{desenvolvimento}}

Utilizaremos de Modelos de Regressão linear para tentar obter
informações que possam indicar como a \emph{sinceridade} e os
\emph{interesses percebidos em comum} influênciam o quanto um
participante do experimento gosta do outro. Para tentar responder essa
pergunta podemos comparar modelos que utilizam \emph{sinceridade e
interesses compartilhados} com outros modelos e comparar métricas de
qualidades desses modelos.

Em modelos de regressão múltipla é necessário determinar um subconjunto
de variáveis independentes que melhor expliquem a variável resposta,
isto é, dentre todas as variáveis explicativas disponíveis, devemos
encontrar um subconjunto de variáveis importantes para o modelo.

Iremos criar um modelo mais abrangente, ou seja, que utiliza mais
variáveis para estimar o valor do like. Além de outras duas variações
desse modelo, removendo 2 variáveis do modelo inicial sendo elas,
\emph{Interesses compartilhados(shar)} e \emph{Sinceridade(sinc)} para a
primeira variação, assim como removendo as 2 variáveis com maior
correlação com a variável like para a segunda variação do modelo.

Nas visualizações de distribuição e correlação abaixo ciano e magenta
serão utilizados, os picos que apresentarem a cor ciano indicam mais
votos de homem naquela faixa e picos com a cor magenta, indicam
predominância de votos de mulheres naquela faixa.

\includegraphics{Speed_dating_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

Percebemos então uma correlação moderada entre as variáveis de
\emph{Interesses Compartilhados} e \emph{Sinceridade} com a variável
dependente, Like.

Se observarmos a correlação das outras variáveis com a variável like,
temos:

\includegraphics{Speed_dating_files/figure-latex/unnamed-chunk-3-1.pdf}

\hypertarget{os-modelos-de-regressuxe3o}{%
\subsubsection{Os Modelos de
Regressão}\label{os-modelos-de-regressuxe3o}}

No total construiremos 3 modelos.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Like sendo explicado pelo máximo de variáveis. Possivelmente o melhor
  modelo que iremos construir pois engloba um maior número de variáveis
  que explicam a variável dependente.
\item
  Like sendo explicado por todas menos `fun' e `attr'. Esse modelo será
  útil para utilizarmos como comparativo dos impactos causados ao
  ignorar duas variáveis que tem maior correlação com a variável
  dependente..
\item
  like sendo explicado por todas menos `sinc' e `shar'. Esse modelo
  ignora as variáveis que gostaríamos de investigar, nos permitindo
  comparar esse modelo com os outros.
\end{enumerate}

\hypertarget{comparando-modelos-de-regressuxe3o}{%
\paragraph{Comparando modelos de
regressão}\label{comparando-modelos-de-regressuxe3o}}

Para o modelo 1, que tem o máximo de variáveis possíveis temos:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo01_m =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{attr }\OperatorTok{+}\StringTok{ }\NormalTok{sinc }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{fun }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{ }\NormalTok{shar }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataMen)  }
\NormalTok{modelo01_w =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{attr }\OperatorTok{+}\StringTok{ }\NormalTok{sinc }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{fun }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{ }\NormalTok{shar }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataWomen)}
\KeywordTok{summary}\NormalTok{(modelo01_m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ attr + sinc + intel + fun + amb + shar + 
##     prob + age_diff, data = dataMen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.4072 -0.5238  0.0311  0.6199  6.4184 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.231328   0.127049   1.821 0.068791 .  
## attr         0.336379   0.015410  21.828  < 2e-16 ***
## sinc         0.070440   0.019608   3.592 0.000336 ***
## intel        0.092374   0.023496   3.932 8.73e-05 ***
## fun          0.196227   0.018588  10.557  < 2e-16 ***
## amb         -0.054537   0.018189  -2.998 0.002748 ** 
## shar         0.173745   0.015083  11.519  < 2e-16 ***
## prob         0.164033   0.012685  12.931  < 2e-16 ***
## age_diff    -0.008695   0.005686  -1.529 0.126394    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.049 on 1983 degrees of freedom
## Multiple R-squared:  0.6436, Adjusted R-squared:  0.6421 
## F-statistic: 447.6 on 8 and 1983 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(modelo01_w)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ attr + sinc + intel + fun + amb + shar + 
##     prob + age_diff, data = dataWomen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.0553 -0.6167  0.0322  0.6308  4.5614 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -4.497e-01  1.149e-01  -3.916 9.32e-05 ***
## attr         2.966e-01  1.539e-02  19.274  < 2e-16 ***
## sinc         9.714e-02  1.717e-02   5.659 1.74e-08 ***
## intel        1.632e-01  2.226e-02   7.330 3.30e-13 ***
## fun          2.028e-01  1.698e-02  11.943  < 2e-16 ***
## amb         -5.733e-03  1.652e-02  -0.347    0.729    
## shar         2.199e-01  1.488e-02  14.777  < 2e-16 ***
## prob         8.328e-02  1.243e-02   6.701 2.67e-11 ***
## age_diff     2.993e-05  5.467e-03   0.005    0.996    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.059 on 2020 degrees of freedom
## Multiple R-squared:  0.7028, Adjusted R-squared:  0.7016 
## F-statistic:   597 on 8 and 2020 DF,  p-value: < 2.2e-16
\end{verbatim}

Para o modelo 2, que não considera `fun' e `attr', temos:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo02_m =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{sinc }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{ }\NormalTok{shar }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataMen)  }
\NormalTok{modelo02_w =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{sinc }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{ }\NormalTok{shar }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataWomen)}
\KeywordTok{summary}\NormalTok{(modelo02_m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ sinc + intel + amb + shar + prob + age_diff, 
##     data = dataMen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.2538 -0.7311  0.0670  0.7719  6.5834 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 1.054601   0.145280   7.259 5.57e-13 ***
## sinc        0.176848   0.022556   7.840 7.27e-15 ***
## intel       0.137088   0.027542   4.977 7.00e-07 ***
## amb         0.038914   0.020941   1.858   0.0633 .  
## shar        0.311257   0.016430  18.944  < 2e-16 ***
## prob        0.187561   0.014904  12.585  < 2e-16 ***
## age_diff    0.002315   0.006687   0.346   0.7293    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.236 on 1985 degrees of freedom
## Multiple R-squared:  0.5041, Adjusted R-squared:  0.5026 
## F-statistic: 336.3 on 6 and 1985 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(modelo02_w)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ sinc + intel + amb + shar + prob + age_diff, 
##     data = dataWomen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7281 -0.7116  0.0758  0.7912  4.6549 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.086022   0.133046   0.647    0.518    
## sinc         0.198383   0.019802  10.018  < 2e-16 ***
## intel        0.231736   0.026117   8.873  < 2e-16 ***
## amb          0.024255   0.019318   1.256    0.209    
## shar         0.400704   0.015575  25.728  < 2e-16 ***
## prob         0.097940   0.014627   6.696 2.77e-11 ***
## age_diff    -0.001263   0.006455  -0.196    0.845    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.25 on 2022 degrees of freedom
## Multiple R-squared:  0.5852, Adjusted R-squared:  0.584 
## F-statistic: 475.5 on 6 and 2022 DF,  p-value: < 2.2e-16
\end{verbatim}

Para o modelo 3, que não considera `sinc' e `shar' temos:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo03_m =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{attr }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{fun }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataMen)  }
\NormalTok{modelo03_w =}\StringTok{ }\KeywordTok{lm}\NormalTok{(like }\OperatorTok{~}\StringTok{ }\NormalTok{attr }\OperatorTok{+}\StringTok{ }\NormalTok{intel }\OperatorTok{+}\StringTok{ }\NormalTok{fun }\OperatorTok{+}\StringTok{ }\NormalTok{amb }\OperatorTok{+}\StringTok{  }\NormalTok{prob }\OperatorTok{+}\StringTok{ }\NormalTok{age_diff, dataWomen)}
\KeywordTok{summary}\NormalTok{(modelo03_m)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ attr + intel + fun + amb + prob + age_diff, 
##     data = dataMen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7400 -0.5348  0.0683  0.6490  5.8862 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  0.188689   0.128134   1.473   0.1410    
## attr         0.364855   0.015747  23.170  < 2e-16 ***
## intel        0.144573   0.021139   6.839 1.06e-11 ***
## fun          0.272436   0.018045  15.097  < 2e-16 ***
## amb         -0.028050   0.018631  -1.506   0.1323    
## prob         0.217174   0.012309  17.644  < 2e-16 ***
## age_diff    -0.014065   0.005863  -2.399   0.0165 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.086 on 1985 degrees of freedom
## Multiple R-squared:  0.6176, Adjusted R-squared:  0.6164 
## F-statistic: 534.2 on 6 and 1985 DF,  p-value: < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(modelo03_w)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = like ~ attr + intel + fun + amb + prob + age_diff, 
##     data = dataWomen)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.3000 -0.6396  0.0694  0.6754  4.5145 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -0.483511   0.121268  -3.987 6.93e-05 ***
## attr         0.345215   0.015980  21.603  < 2e-16 ***
## intel        0.229619   0.020911  10.981  < 2e-16 ***
## fun          0.301058   0.016777  17.945  < 2e-16 ***
## amb          0.018221   0.017441   1.045    0.296    
## prob         0.147806   0.012457  11.866  < 2e-16 ***
## age_diff     0.005539   0.005785   0.957    0.338    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.123 on 2022 degrees of freedom
## Multiple R-squared:  0.6654, Adjusted R-squared:  0.6644 
## F-statistic: 670.1 on 6 and 2022 DF,  p-value: < 2.2e-16
\end{verbatim}

\hypertarget{comentando-muxe9tricas-dos-modelos}{%
\subsubsection{Comentando métricas dos
modelos}\label{comentando-muxe9tricas-dos-modelos}}

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}

\hypertarget{significuxe2ncia}{%
\paragraph{Significância:}\label{significuxe2ncia}}

Nas métricas dos modelos análisados temos códigos de significância para
indicar variáveis que podem estar relacionadas com a variável resposta
que procuramos ou não.

\hypertarget{modelo-1}{%
\subparagraph{Modelo 1}\label{modelo-1}}

Para o modelo dos homens vemos que a diferença de idade entre as pessoas
no encontro não parece ser significante para o modelo. Já para as
mulheres além da diferença de idade, a ambição que a mulher julgava
compartilhar com a pessoa que ela se encontrou não parece ser relevante
para o like.

\hypertarget{modelo-2-sem-fun-e-attr}{%
\subparagraph{Modelo 2 (sem fun e attr)}\label{modelo-2-sem-fun-e-attr}}

Para o modelo dos homens vemos que a diferença de idade continua sem ser
significante para o modelo porém a ambição (amb) percebida perde um
pouco a significância. Já para as mulheres a ambição e diferença de
idade são variáveis que não parecem estar ligadas ao ``like''.

\hypertarget{modelo-3-sem-sinc-e-shar}{%
\subparagraph{Modelo 3 (sem sinc e
shar)}\label{modelo-3-sem-sinc-e-shar}}

Para o modelo dos homens vemos que a diferença de idade ganha um pouco
de significância, porém a ambição (amb) percebida tem
Pr(\textgreater{}\textbar{}t\textbar{}) muito alta pra ser considerado
significante. Já para as mulheres a ambição e diferença de idade
continuam sem estar ligadas ao ``like''.

\hypertarget{relevuxe2ncia-e-magnitude-dos-coeficientes}{%
\subsubsection{Relevância e Magnitude dos
Coeficientes:}\label{relevuxe2ncia-e-magnitude-dos-coeficientes}}

Neste caso os coeficientes estão variando de 0 a 1, dando uma
característica de peso a uma certa característica. Ou seja, quanto maior
o coeficiente relacionado a uma certa característica, maior a influência
que aquele atributo terá naquele modelo.

\hypertarget{modelo-1-1}{%
\subparagraph{Modelo 1}\label{modelo-1-1}}

Os fatores mais importantes são `attr'(aparência) e `fun'(Quão divertida
a outra pessoa parecia) e `attr e shar'(interesses compartilhados), para
homens e mulheres respectivamente.

\hypertarget{modelo-2}{%
\subparagraph{Modelo 2}\label{modelo-2}}

Os fatores mais importantes para esse modelo são `shar e
prob'(Probabilidade de querer se ver de novo) e `shar e
intel'(inteligência percebida) para homens e mulheres respectivamente.

\hypertarget{modelo-3}{%
\subparagraph{Modelo 3}\label{modelo-3}}

Os fatores mais importantes para esse modelo são `attr e fun' e `attr e
fun'(Quão divertido o ouro é) para homens e mulheres respectivamente.

\hypertarget{r-squared-e-r-squared-adjusted}{%
\subsubsection{R Squared e R Squared
Adjusted:}\label{r-squared-e-r-squared-adjusted}}

R Squared indica uma medida de quão bem o modelo se ajusta aos dados. É
uma medida que varia de 0 a 1, onde 0 representa um modelo que não se
adequa aos dados e valores próximos a 1, indicam modelos que se ajustam
bem aos dados.

\hypertarget{modelo-1-2}{%
\subparagraph{Modelo 1}\label{modelo-1-2}}

Os valores de R² pra esse modelo são os mais altos de todos os modelos,
geralmente um número mais de variáveis pode aumentar o R² de um modelo.

\hypertarget{modelo-2-1}{%
\subparagraph{Modelo 2}\label{modelo-2-1}}

O menor valor de R² de todos os modelos, o que indica que a percepção de
quão atrativa e legal a outra pessoa é, é bastante importante para a
variável que queremos estimar.

\hypertarget{modelo-3-1}{%
\subparagraph{Modelo 3}\label{modelo-3-1}}

Ao remover `sinc' e `shar', também temos uma degradação do modelo porém
temos um modelo que explica melhor a variável independente do que o
modelo 2.

\hypertarget{resuxedduos}{%
\subsubsection{Resíduos}\label{resuxedduos}}

Nas métricas de qualidade acima \emph{Residual Standard Error} é a
medida de ajuste do modelo de regressão. Teóricamente, todo modelo de
regressão linear tem um erro associado \textbf{\emph{E}}. Devido a
presença desse erro não somos capazes de predizer perfeitamente a
variável \emph{like} apartir das outras variáveis, sendo assim o
\emph{Residual Standard Error} (erro padrão residual) é o uma média da
diferença entre as estimativas versus os dados reais observados. Ou
seja, ao estimar, é provável que exista uma diferença entre a estimativa
e o valor do like real com a magnitude do erro residual padrão.

\hypertarget{modelo-1-3}{%
\subparagraph{Modelo 1}\label{modelo-1-3}}

O erro residual padrão é 1.05. Lembrando que segundo as métricas esse
até agora é o nosso melhor modelo.

\hypertarget{modelo-2-2}{%
\subparagraph{Modelo 2}\label{modelo-2-2}}

O erro residual padrão é 1.236 e 1.25. Com menos variáveis e um R² menor
do que o modelo 1, o erro residual padrão aumenta como era de se
esperar.

\hypertarget{modelo-3-2}{%
\subparagraph{Modelo 3}\label{modelo-3-2}}

O erro residual padrão é 1.086 e 1.123. Como vimos além do R² desse
modelo ser melhor, ou seja um pouco maior do que o R² do modelo 2, o
erro residual padrão também é menor.

\hypertarget{conclusuxf5es}{%
\subsection{Conclusões}\label{conclusuxf5es}}

Neste relatório utilizamos de modelos lineares para tentar explicar
características que possam influenciar um indivíduo gostar de outro em
um encontro relâmpago, ou speed dating. Partimos de modelos mais
simples, para modelos mais complexos analisando o quão bem o modelo em
questão explica a variável independente.

Neste processo identificamos que algumas variáveis como a diferença de
idade entre os individuos, não parecem influenciar na qualidade do
modelo ou até ter impactos negativos, introzindo ruído e diminuíndo a
eficácia do modelo.

Além disso, verificamos que as duas variáveis independentes influênciam
mais no modelo para mulheres, ou seja, as mulheres se importam mais com
o interesse em comum e a sinceridade do que os homens, de acordo com
esse experimento. Por fim, percebemos também que a variável que
representa o interesse em comum tem mais influência que a sinceridade.

Um modelo de regressão ideal, explicaria toda a variância e teria
portanto uma métrica próxima a 1. Porém existem fatores aleatórios que
não foram considerados pelo modelo que poderiam afetar a qualidade do
mesmo, por exemplo, as cidades de origem dos indivíduos e por
consequência a distância entre os indivíduos, se são da mesma etnia,
etc.

De tal forma que parece improvável que um modelo de regressão linear
seja capaz de acertar com perfeição o like baseado nas respostas dos
questionários após os encontros de 4 minutos.

\begin{center}\rule{0.5\linewidth}{\linethickness}\end{center}


\end{document}
